# Generated by Django 3.2.5 on 2024-02-21 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20240221_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todonote',
            old_name='note',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='todonote',
            old_name='complete',
            new_name='status',
        ),
    ]
