# Generated by Django 3.2.5 on 2021-11-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo_App', '0002_alter_todonote_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todonote',
            name='category',
            field=models.CharField(choices=[('General', 'General'), ('Body Exercise', 'Body Exercise'), ('Learning', 'Learning'), ('Chores', 'Chores')], default='General', max_length=20),
        ),
    ]
